import BackBtn from '@/components/button/BackPageBtn';
import SubmitBtn from '@/components/button/SubmitBtn';
import RatingCard from '@/components/middleCards/RatingCard';
import PairingCardController from '@/components/pairing/PairingCardController';
import Router from 'next/router';

import Head from 'next/head';
import { useEffect, useState } from 'react';
export default function UserPage() {
  const pairingCardProps = {
    data: [
      {
        beerId: 1,
        pairingId: 1,
        nickname: '김맥주',
        content: '수정된 페어링',
        thumbnail:
          'https://worldbeermarket.kr/userfiles/prdimg/2102080006_M.jpg',
        category: 'SNACK',
        likeCount: 3,
        commentCount: 0,
        isUserLikes: true,
        createdAt: '2023-02-06T00:29:14.59836',
        modifiedAt: '2023-02-06T00:31:11.1951',
      },
      {
        beerId: 1,
        pairingId: 2,
        nickname: '김맥주',
        content: '페어링 안내',
        thumbnail:
          'https://worldbeermarket.kr/userfiles/prdimg/2301050762_R.jpg',
        category: 'GRILL',
        likeCount: 2,
        commentCount: 0,
        isUserLikes: false,
        createdAt: '2023-02-06T00:35:58.259552',
        modifiedAt: '2023-02-06T00:35:58.259552',
      },
    ],
    pageInfo: {
      page: 1,
      size: 5,
      totalElements: 2,
      totalPages: 1,
    },
  };

  const [curTab, setCurTab] = useState(0);
  const tabArr = [
    {
      name: '평가',
      content: (
        <PairingCardController pairingCardProps={pairingCardProps.data} />
      ),
    },
    {
      name: '페어링',
      content: (
        <PairingCardController pairingCardProps={pairingCardProps.data} />
      ),
    },
  ];
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-md">
        <BackBtn></BackBtn>
        <div>
          <div className="flex gap-3 p-2 justify-center">
            <div className="bg-y-cream h-24 w-24 rounded-full "></div>
            <div className="p-1 self-center">
              <div>성유미님</div>
              <div className="text-xs mb-2">평가 1 페어링 2 댓글 2</div>
              <div className="flex gap-2">
                <div
                  className="bg-y-cream py-2 px-3 rounded-lg text-xs cursor-pointer"
                  onClick={() => Router.push('/follower/1')}
                >
                  10 팔로워
                </div>
                <div className="bg-y-cream py-2 px-3 rounded-lg text-xs cursor-pointer">
                  10 팔로잉
                </div>
              </div>
            </div>
          </div>
          <SubmitBtn onClick={undefined}>팔로우</SubmitBtn>
        </div>
        <div className="border rounded-lg m-1 p-2">
          <ul className="flex justify-around mt-1 mb-4">
            {tabArr.map((el, idx) => {
              return (
                <li
                  key={idx}
                  className={
                    curTab === idx
                      ? 'text-y-brown border-b-2 border-y-brown px-2 cursor-pointer'
                      : 'text-y-gray px-2 cursor-pointer'
                  }
                  onClick={() => setCurTab(idx)}
                >
                  {el.name}
                </li>
              );
            })}
          </ul>
          {tabArr[curTab].content}
        </div>
      </main>
    </>
  );
}
