import Head from 'next/head';
import SortBox, { Sort } from '@/components/selectBox/SortBox';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import PairingBox from '@/components/selectBox/PairingBox';
import PairingCardController from '@/components/pairing/PairingCardController';
import axios from '@/pages/api/axios';

export default function AllPairing() {
  let router = useRouter();
  const [curRoute, setCurRoute] = useState<any>();
  const [sort, setSort] = useState<Sort>('mostlikes');
  const [category, setCategory] = useState<string>('ALL');
  const [pairingCardProps, setPairingCardProps] = useState<any>();
  useEffect(() => {
    setCurRoute(router.query.id);
  }, [router, curRoute]);
  useEffect(() => {
    if (curRoute !== undefined) {
      axios
        .get(`/pairings/page/${sort}?beerId=${curRoute}&page=1&size=5`)
        .then((response) => setPairingCardProps(response.data))
        .catch((error) => {
          console.log(error);
        });
    }
  }, [curRoute, sort]);

  //   data: [
  //     {
  //       beerId: 1,
  //       pairingId: 1,
  //       nickname: '김맥주',
  //       content: '수정된 페어링',
  //       thumbnail:
  //         'https://worldbeermarket.kr/userfiles/prdimg/2102080006_M.jpg',
  //       category: 'SNACK',
  //       likeCount: 3,
  //       commentCount: 0,
  //       isUserLikes: true,
  //       createdAt: '2023-02-06T00:29:14.59836',
  //       modifiedAt: '2023-02-06T00:31:11.1951',
  //     },
  //     {
  //       beerId: 1,
  //       pairingId: 2,
  //       nickname: '김맥주',
  //       content: '페어링 안내',
  //       thumbnail:
  //         'https://worldbeermarket.kr/userfiles/prdimg/2301050762_R.jpg',
  //       category: 'GRILL',
  //       likeCount: 2,
  //       commentCount: 0,
  //       isUserLikes: false,
  //       createdAt: '2023-02-06T00:35:58.259552',
  //       modifiedAt: '2023-02-06T00:35:58.259552',
  //     },
  //   ],
  //   pageInfo: {
  //     page: 1,
  //     size: 5,
  //     totalElements: 2,
  //     totalPages: 1,
  //   },
  // };
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl border">
        <div className="mt-4 text-center bg-white rounded-lg max-w-4xl font-semibold">
          제주슬라이스
        </div>
        <div className="m-auto flex">
          <SortBox setSort={setSort} />
          <PairingBox setCategory={setCategory} />
        </div>
        <PairingCardController pairingCardProps={pairingCardProps?.data} />
        <div className="pb-32"></div>
      </main>
    </>
  );
}
