import Head from 'next/head';
import Image from 'next/image';
import SmallRatingCard from '@/components/smallCards/SmallRatingCard';
import SmallPairingCard from '@/components/smallCards/SmallPairingCard';
import SimilarBeer from '@/components/smallCards/SimilarBeer';
import RatingTitle from '@/components/beerPage/RatingTitle';
import PairingTitle from '@/components/beerPage/PairingTitle';
import BeerDetailCard from '@/components/beerPage/BeerDetailCard';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import { currentBeer } from '@/atoms/currentBeer';
import axios from '@/pages/api/axios';

export default function Beer() {
  let router = useRouter();
  const [curRoute, setCurRoute] = useState<any>();
  useEffect(() => {
    setCurRoute(router.query.id);
  }, [router, curRoute]);

  const [beerInfo, setBeerInfo] = useState<any>();
  const [, setCurBeer] = useRecoilState(currentBeer);
  const [commentInfo, setCommentInfo] = useState<any>();
  const [pairingInfo, setPairingInfo] = useState<any>();
  const [similarBeer, setSimilarBeer] = useState<any>();

  useEffect(() => {
    // 특정 맥주 조회
    if (curRoute !== undefined) {
      axios
        .get(`/api/beers/${curRoute}`)
        .then((response) => {
          setBeerInfo(response.data);
          setCurBeer(response.data);
        })
        .catch((error) => console.log(error));
    }
  }, [curRoute, setCurBeer]);

  useEffect(() => {
    // 코멘트 페이지 조회
    if (curRoute !== undefined) {
      axios
        .get(`/api/ratings/page/recency?beerId=${curRoute}&page=1&size=5`)
        .then((response) => setCommentInfo(response.data))
        .catch((error) => console.log(error));
    }
  }, [curRoute]);

  useEffect(() => {
    // 페어링 페이지 조회
    if (curRoute !== undefined) {
      axios
        .get(`/api/pairings/page/recency?beerId=${curRoute}&page=1&size=5`)
        .then((response) => {
          setPairingInfo(response.data);
        })
        .catch((error) => console.log(error));
    }
  }, [curRoute]);

  useEffect(() => {
    // 비슷한 맥주 조회
    if (curRoute !== undefined) {
      axios
        .get(`/api/beers/${curRoute}/similar`)
        .then((response) => {
          setSimilarBeer(response.data);
        })
        .catch((error) => console.log(error));
    }
  }, [curRoute]);

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="m-auto h-screen max-w-4xl relative">
        <Image
          className="w-full h-screen left-0 top-0 fixed -z-10 select-none"
          src="/images/background.png"
          alt="bg"
          width={500}
          height={500}
        />

        <div className="m-3">
          <BeerDetailCard cardProps={beerInfo} />
        </div>

        <RatingTitle
          ratingCount={commentInfo?.pageInfo?.totalElements}
          beerId={curRoute}
        />
        <SmallRatingCard ratingProps={commentInfo?.data} />

        <PairingTitle
          pairngCount={pairingInfo?.pageInfo?.totalElements}
          beerId={curRoute}
        />
        <SmallPairingCard pairingProps={pairingInfo?.data} />
        <SimilarBeer similarBeer={similarBeer} />
        <div className="h-20"></div>
      </main>
    </>
  );
}
