import BackBtn from '@/components/button/BackPageBtn';
import SubmitBtn from '@/components/button/SubmitBtn';
import FollowUser from '@/components/followPage/FollowUser';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from '@/pages/api/axios';

export default function Follower() {
  const router = useRouter();
  const { id } = router.query;
  const state = router.query.state;
  const [curTab, setCurTab] = useState(Number(state));

  // const tabArr = [
  //   {
  //     name: '팔로워',
  //     content: <FollowUser />,
  //   },
  //   {
  //     name: '팔로잉',
  //     content: <FollowUser />,
  //   },
  // ];
  // useEffect(() => {
  //   if (id !== undefined) {
  //     axios
  //       .get(`/api/follows/${id}/followings`)
  //       .then((res) => {
  //         console.log(res.data);
  //       })
  //       .catch((error) => console.log(error));
  //   }
  // }, [id]);
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-md">
        <BackBtn></BackBtn>
        <div>
          {/* <ul className="flex justify-around mb-4">
            {tabArr.map((el, idx) => {
              return (
                <li
                  key={idx}
                  className={
                    curTab === idx
                      ? 'text-y-brown border-b-2 border-y-brown px-2 cursor-pointer'
                      : 'text-y-gray px-2 cursor-pointer'
                  }
                  onClick={() => setCurTab(idx)}
                >
                  {el.name}
                </li>
              );
            })}
          </ul>
          {tabArr[curTab].content} */}
        </div>
      </main>
    </>
  );
}
