import BackBtn from '@/components/button/BackPageBtn';
import SubmitBtn from '@/components/button/SubmitBtn';
import FollowUser from '@/components/followPage/FollowUser';
import Head from 'next/head';
import { useState, useEffect } from 'react';

export default function Follower() {
  const [curTab, setCurTab] = useState(1);
  const tabArr = [
    {
      name: '팔로잉',
      content: <FollowUser />,
    },
    {
      name: '팔로워',
      content: <FollowUser />,
    },
  ];
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-md">
        <BackBtn></BackBtn>
        <div>
          <ul className="flex justify-around mb-4">
            {tabArr.map((el, idx) => {
              return (
                <li
                  key={idx}
                  className={
                    curTab === idx
                      ? 'text-y-brown border-b-2 border-y-brown px-2 cursor-pointer'
                      : 'text-y-gray px-2 cursor-pointer'
                  }
                  onClick={() => setCurTab(idx)}
                >
                  {el.name}
                </li>
              );
            })}
          </ul>
          {tabArr[curTab].content}
        </div>
      </main>
    </>
  );
}
