import BackBtn from '@/components/button/BackPageBtn';
import FollowUser, { FollowProps } from '@/components/followPage/FollowUser';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from '@/pages/api/axios';
import Image from 'next/image';
import Pagenation from '@/components/Pagenation';
import { useRecoilState } from 'recoil';
import { accessToken } from '@/atoms/login';

export default function Follower() {
  const router = useRouter();
  const userid = router.query.id;
  const [followerList, setFollowerList] = useState<FollowProps[]>([]);
  const [page, setPage] = useState<number>(1);
  const [totalPages, setTotalPages] = useState<number>(1);
  const [TOKEN] = useRecoilState(accessToken);
  useEffect(() => {
    const config = {
      headers: { Authorization: TOKEN, 'Content-Type': 'application/json' },
      withCredentials: true,
    };
    if (userid !== undefined) {
      axios
        .get(`/api/follows/${userid}/followers?page=${page}`, config)
        .then((res) => {
          setFollowerList(res.data.data);
          setTotalPages(res.data.pageInfo.totalPages);
        })
        .catch((error) => console.log(error));
    }
  }, [TOKEN, page, userid]);

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-md">
        <BackBtn></BackBtn>
        <div>
          <div className="my-8 text-center text-xl bg-white font-semibold">
            팔로워
          </div>
          {followerList.length === 0 ? (
            <div className="noneContent">
              <Image
                className="m-auto pb-3 opacity-50"
                src="/images/logo.png"
                alt="logo"
                width={40}
                height={40}
              />
              팔로워가 없습니다.
            </div>
          ) : (
            <div className="m-2 border divide-y divide-gray-200 rounded-xl">
              {followerList.map((el: FollowProps) => (
                <div key={el.userId}>
                  <FollowUser followprops={el} />
                </div>
              ))}
            </div>
          )}
        </div>

        {followerList.length ? (
          <Pagenation page={page} setPage={setPage} totalPages={totalPages} />
        ) : null}
      </main>
    </>
  );
}
