import SubmitBtn from '@/components/button/SubmitBtn';
import NavBar from '@/components/NavBar';
import { Input } from '@/components/inputs/Input';
import Head from 'next/head';
import { IoClose, IoArrowForwardOutline } from 'react-icons/io5';
export default function Login() {
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    console.log(event.target);
    console.log(event.currentTarget);
  };
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <button className="m-4">
          <IoClose className="w-6 h-6" />
        </button>
        <div className="my-7 text-center text-lg bg-white rounded-lg max-w-4xl font-semibold">
          로그인
        </div>
        <div className="m-2 border-b-1 border-y-gray">
          <Input type="email" placeholder="email@gmail.com" />
          <Input type="password" placeholder="비밀번호를 입력하세요." />
          <SubmitBtn onClick={handleClick}> 로그인 </SubmitBtn>
          <div className="m-4 flex justify-center gap-1.5 text-sm">
            <div className="text-y-gray">만약 계정이 없다면?</div>
            <button className="flex text-y-brown">회원가입</button>
          </div>
        </div>
        <NavBar />
      </main>
    </>
  );
}
