import Head from 'next/head';
import BigInput from '@/components/inputs/BigInput';
import PairingSelect from '@/components/selectBox/PairingSelect';
import ImageUpload from '../../components/postPairingPage/ImageUpload';
import PostDetailCard from '@/components/postPairingPage/PostDetailCard';
import CloseBtn from '@/components/button/CloseBtn';
import SubmitBtn from '@/components/button/SubmitBtn';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { useRecoilState } from 'recoil';
import { currentBeer } from '@/atoms/currentBeer';
import axios from '@/pages/api/axios';

export default function PostPairing() {
  const router = useRouter();
  const [beerInfo] = useRecoilState(currentBeer);

  const [content, setContent] = useState('');
  const [category, setCategory] = useState('카테고리');
  const [imageData, setImageData] = useState([]);
  const [jsonData, setJsonData] = useState({
    beerId: beerInfo.beerId,
    // userId: 1,
    content: '',
    category: '',
  });
  const [finalData, setFinalData] = useState<any>('');

  // userInfo 로직, userId가 필요하다.
  const [userInfo, setUserInfo] = useState();
  const [TOKEN, setTOKEN] = useState();
  // useEffect(() => {
  //   const localInfo = window.localStorage.getItem('recoil-persist');
  //   if (localInfo !== null) {
  //     const tmpData = JSON.parse(localInfo);
  //     setTOKEN(tmpData.accessToken);

  //     const config = {
  //       headers: {
  //         authorization: TOKEN,
  //         'content-type': 'multipart/form-data',
  //       },
  //       withCredentials: true,
  //     };
  //     axios
  //       .get(`/api/user`, config)
  //       .then((response) => setUserInfo(response.data))
  //       .catch((error) => console.log(error));
  //   }
  // }, [TOKEN]);
  // console.log('userInfo', userInfo);

  // Vaild 로직
  const [isValid, setIsValid] = useState(false);
  const [isSubmit, setIsSubmit] = useState(false);
  useEffect(() => {
    if (content.length >= 3 && category !== '카테고리') setIsValid(true);
    else setIsValid(false);
  }, [content, category]);

  // Post 제출 로직
  const handleSubmit = () => {
    setJsonData({
      beerId: beerInfo.beerId,
      // userId: 1,
      content: content,
      category: category,
    });

    const formData = new FormData();
    for (const file of imageData) {
      formData.append('files', file);
    }
    formData.append(
      'post',
      new Blob([JSON.stringify(jsonData)], { type: 'application/json' })
    );
    setFinalData(formData);
  };
  // Submit 과 formData 변경 감지 후 로직
  useEffect(() => {
    const config = {
      headers: {
        'content-type': 'multipart/form-data',
      },
      withCredentials: true,
    };
    if (finalData !== '' && !isSubmit) {
      // console.log(jsonData);
      axios
        .post(`/api/pairings`, finalData, config)
        .then((response) => {
          console.log(response);
          router.back();
          setIsSubmit(true);
        })
        .catch((error) => console.log(error));
    }
  }, [finalData, router, isSubmit]);

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="m-auto h-screen max-w-4xl">
        <div className="p-5">
          <PostDetailCard beerInfo={beerInfo} />
          <div className="mt-6 mb-2 text-base font-semibold">
            페어링 카테고리
          </div>
          <PairingSelect category={category} setCategory={setCategory} />
          <ImageUpload imageData={imageData} setImageData={setImageData} />
          <div className="mt-6 mb-2 text-base font-semibold">설명</div>
          <BigInput
            placeholder="세글자 이상 적어주세요"
            inputState={content}
            setInputState={setContent}
          />
        </div>
        <div className="flex">
          <div className="flex-1">
            <CloseBtn onClick={() => router.back()}>나가기</CloseBtn>
          </div>
          <div className="flex-1">
            {isValid ? (
              <SubmitBtn onClick={handleSubmit}>등록하기</SubmitBtn>
            ) : (
              <div className="flex justify-center items-center w-full h-11 rounded-xl m-2 bg-red-100 text-xs text-red-500 -ml-[1px]">
                카테고리와 내용을 추가하세요
              </div>
            )}
          </div>
        </div>
        <div className="h-20"></div>
      </main>
    </>
  );
}
