import Head from 'next/head';
import NavBar from '@/components/NavBar';
import BigInput from '@/components/inputs/BigInput';
import PairingBox from '@/components/selectBox/PairingBox';
import ImageUpload from './ImageUpload';

export default function PostPairing() {
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="m-auto h-screen max-w-4xl">
        <PairingBox />
        <BigInput placeholder="페어링을 추천하시는 이유를 적어주세요" />
        <ImageUpload />
        <NavBar />
      </main>
    </>
  );
}
