import Head from 'next/head';
import Image from 'next/image';
import NavBar from '@/components/NavBar';
import SmallCardController from '@/components/SmallCardController';
import SmallpairingController from '@/components/SmallpairingController';

export default function Main() {
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className="h-screen m-auto max-w-4xl">
        <div>
          <main className="m-auto border-2 pb-14">
            <div className="py-2 bg-gray-200 text-black">상단헤더</div>
            <Image
              className="m-auto"
              src="/images/adv.jpg"
              alt="adv"
              width={500}
              height={500}
              priority
            />
            <div className="m-auto">
              레이팅 소 카드
              <SmallCardController />
              페어링 소 카드
              <SmallpairingController />
            </div>
          </main>
          <NavBar />
        </div>
      </div>
    </>
  );
}
