import Head from 'next/head';
import Image from 'next/image';

export default function Main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="py-2 bg-gray-200 text-black">네비게이션바</div>
        <div className="py-2 bg-gray-200 text-black">
          <Image
            // className=""
            src="/images/adv.jpg"
            alt="adv"
            width={1000}
            height={1000}
            priority
          />
        </div>
      </main>
    </>
  );
}
