########################################################################################
##                                                                                    ##
##                          Crawling Path and Beer List                               ##
##                                                                                    ##
########################################################################################

START_URL = 'https://www.ratebeer.com/beer/jeju-baengnokdam-ale/58057/'
SEARCH_BOX = '/html/body/div[1]/div[2]/header/div[2]/div[1]/div[2]/div/div/input'
TARGET_XPATH = '//*[@id="root"]/div[2]/div[2]/div/div/div/div[2]/div[1]/div[1]'

TEST_LIST = ['APPLE FOX', 'ARK LAGER', 'ASAHI', 'ASAHI SUPER DRY', 'BABE GRIGIO WITH BUBBLES',
             'BABE RED WINE WITH BUBBLES', 'BABE ROSE WINE WITH BUBBLES', 'BAVARIA LEMON', 'BEAR BEER LAGER', 'BECK’S',
             'BIG WAVE', 'BIG WAVE GOLDEN ALE', 'BLUE GIRL', 'BLUE GIRL PILSENER LAGER', 'BLUE MOON',
             'BUDEJOVICKY BUDVAR', 'BUDWEISER', 'CACAO S STOUT BEER', 'CAFRI', 'CARLSBERG', 'CASS ZERO',
             'CHANG CLASSIC', 'CHANG ESPRESSO LAGER', 'CHIMAY GOLD', 'CHIMAY GRANDE RESERVE', 'CHIMAY PERES TRAPPISTES',
             'CHIMAY PERES TRAPPISTES TRIPLE', 'COORS', 'CORONA EXTRA', 'CORSENDONK PATER DUBBEL ALE',
             'CRUISER RASPBERRY', 'CUTWATER TEQUILA MARGARITA', 'DEAR J LAGER', 'DEAR J PEACH ALE',
             'DESCHUTES FRESH HAZE', 'DESPRADOS ORIGINAL', 'DUCHESSE DE BOURGOGNE', 'DUCK DUCK GOOSE SESSION IPA',
             'DUVEL', 'DUVEL 6,66', 'EDELWEISS', 'EDELWEISS PEACH', 'EFES PILSNER', 'EGGER GRAPEFRUIT RADLER',
             'EGGER PFIRSICH RADLER', 'EGGER TRAUBEN RADLER', 'EGGER ZITRONEN RADLER', 'ERDINGER WEISSBIER',
             'ESTELLA GALICIA', 'ESTRELLA DAMM', 'FIRE ROCK PALE ALE', 'FIZZ CIDER APPLE', 'FIZZ CIDER BLUEBERRY',
             'FIZZ CIDER PEAR', 'FIZZ CIDER STRAWBERRY', 'GAFFEL KOLSCH', 'GAFFEL LEMON', 'GEUMGANGSAN GOLDEN ALE',
             'GOGILDONG ALE', 'GOLMOG DAEJANG GOLD ALE', 'GOMPYO SUMMER ALE', 'GOMPYO WHEAT BEER', 'GOOSE IPA',
             'GOOSE ISLAND 312', 'GOOSE ISLAND 312 URBAN WHEAT ALE', 'GOOSE ISLAND IPA', 'GREVENSTEINER ORIGINAL',
             'GRIMBERGEN BLANCHE', 'GUINESS EXTRA STOUT', 'GUINNESS DRAUGHT', 'HANALEI ISLAND IPA',
             'HAND & APPLE CIDER APPLE', 'HAND & APPLE CIDER WATERMELON & CUCUMBER', 'HANOK VILLAGE ALE', 'HARBIN',
             'HEINEKEN', 'HEINEKEN SILVER', 'HITE ZERO', 'HOBGOBLIN GOLD', 'HOBGOBLIN RUBY', 'HOEGAARDEN',
             'HOEGAARDEN BOTANUC', 'HOEGAARDEN FRUIT BREW PEAR', 'HOEGAARDEN FRUIT BREW ROSE',
             'HOEGAARDEN NON ALCOHOLIC', 'HOEGAARDEN PEAR', 'HOEGAARDEN ROSE', 'HOEGAARDEN WITBIER',
             'HOP HOUSE 13 LAGER', 'INDICA IPA', 'INEDIT DAMM', 'JEJU GEOMEONG ALE', 'JEJU LAGER', 'JEJU PELLONG ALE',
             'JEJU SLICE', 'JEJU WIT ALE', 'JIN DA LAI BEER', 'KABREW ENERGE BEER', 'KAISERDOM KELLERBIER',
             'KAISERDOM PILSENER', 'KINGFISHER PREMIUM LAGER BEER', 'KIRIN ICHBAN', 'KKANG BEER BLACK',
             'KKANG BEER ORIGINAL', 'KLOUD HARD SELTZER MANGO', 'KONA LONGBOARD ISLAND LAGER', 'KOZEL DARK',
             'KOZEL LAGER', 'KOZEL PREMIUM LAGER', 'KROMBACHER PILS', 'KROMBACHER WEIZEN', 'KRONENBOURG 1664',
             'KRONENBOURG 1664 BLANC', 'KUMIHO IPA', 'KUMIHO PEACH ALE', 'KUMIHO RELAX BEER', 'LEFFE BLOND',
             'LEFFE BRUNE', 'LEO', 'LETS FRESH TODAY', 'LINDEMANS APPLE', 'LINDEMANS KRIEK', 'LINDEMANS PECHERESSE',
             'LION LAGER', 'LION STOUT', 'LONGBOARD ISLAND LAGER', 'MAKKU', 'MAKKU BLUEBERRY', 'MAKKU MANGO',
             'MICHELOB ULTRA', 'MURPHY’S IRISH STOUT', 'NORTH COAST OLD RASPUTIN RUSSIAN IMPERIAL STOUT',
             'PAKKA HARD SELTZER BLACK CHERRY', 'PAKKA HARD SELTZER CHERRY LIME',
             'PAKKA HARD SELTZER GRAPEFRUIT TANGERINE', 'PAKKA HARD SELTZER MIXED BERRY', 'PATAGONIA BOHEMIAN PILSENER',
             'PAULANER MUNICHI LAGER', 'PAULANER WEISSBIER', 'PAULANER WEISSBIER DUNKEL', 'PERONI NASTRO AZZURRO',
             'PILSMER URQUELL', 'PLATINUM STANDARD OF ALE', 'REEPER B. INDIA PALE ALE', 'SAMUEL ADAMS BOSTON LAGER',
             'SAN MIGUEL', 'SAN MIGUEL CERVEZA BLANCA', 'SAN MIGUEL NAB', 'SAN MIGUEL PALE PILSEN', 'SAPPORO',
             'SAPPORO PREMIUM', 'SAPPORO PREMIUM BEER', 'SCHOEFFER HOFER GRAPEFRUIT', 'SEOKBINGO LAGER BEER',
             'SEOUL FOREST LAGER', 'SEOUL FOREST PILSNER', 'SINGHA', 'SINGHA BEER', 'SMILEY BEER', 'SMILEY MALDIVES',
             'SOMERSBY APPLE', 'SSG LANDERS LAGER', 'STELLA ARTOIS', 'STIEGL GOLDBRAU', 'STIEGL GRAPERUIT',
             'STIEGL RADLER GRAPEFRUIT', 'STIEGL RADLER ZITRONE', 'STIEGL ZITRONE', 'STONE IPA',
             'SUNTORY PREMIUM MALTS', 'SUPER STARS PALE ALE', 'TASANGJU', 'TEMPT NO 7', 'TEMPT NO 9',
             'THE IRON SQUAD BEER', 'TIGER', 'TIGER LAGER', 'TIGER RADLER GRAPEFRUIT', 'TIGER RADLER LEMON',
             'TIKI RUM MAI TAI', 'TROLL BREW HEFE GRAPEFRUIT', 'TROLL BREW LEMON RADLER', 'TSINGTAO',
             'TSINGTAO PREMIUM LAGER', 'TSINGTAO PURE DRAFT', 'TSINGTAO STOUT', 'TSINGTAO WHEAT BEER',
             'TWILGHT AMERICAN PALE ALE', 'VODCA SODA', 'VOLFAS ENGELMAN', 'VOLFAS ENGELMAN BLANC',
             'VOLFAS ENGELMAN HEFEWEIZEN', 'VOLFAS ENGELMAN IPA', 'VOLFAS ENGELMAN PREMIUM LAGER',
             'WARSTEINER PREMIUM PILSNER', 'WEIHENSTEPHAN HEFEWEISSBIER', 'WEIHENSTEPHAN HEFEWEISSBIER DUNKEL',
             'WEIHENSTEPHAN KRISTALL WEISSBIER', 'YEBISU', 'YOUNG BOSS']
