import Head from 'next/head';
import Image from 'next/image';
import { useRecoilState } from 'recoil';
import { accessToken, userId, userNickname } from '@/atoms/login';
import { useEffect, useState } from 'react';
import axios from '@/pages/api/axios';
import Link from 'next/link';
import {
  IoHeartOutline,
  IoChevronForwardOutline,
  IoChatboxEllipsesOutline,
  IoLogOutOutline,
} from 'react-icons/io5';
import {
  HiPencil,
  HiOutlinePencil,
  HiOutlineChartPie,
  HiOutlineMapPin,
} from 'react-icons/hi2';
import swal from 'sweetalert2';
import { useRouter } from 'next/router';

export default function Mypage() {
  const router = useRouter();
  const [TOKEN, setAccessToken] = useRecoilState(accessToken);
  const [USERID, setUserId] = useRecoilState(userId);
  const [userName, setUserName] = useRecoilState(userNickname);
  const [followingCount, setFollowingCount] = useState(0);
  const [followerCount, setFollowerCount] = useState(0);
  const [follow, setFollow] = useState(false);
  const [userImg, setUserImg] = useState('');
  const [name, setName] = useState('');
  useEffect(() => {
    if (TOKEN) {
      axios
        .get('/api/user')
        .then((res) => {
          setUserName(res.data.nickname);
          setFollowerCount(res.data.followerCount);
          setFollowingCount(res.data.followingCount);
          setUserImg(res.data.imageUrl);
          setFollow(res.data.isFollowing);
          setName(res.data.nickname);
        })
        .catch((err) => console.log(err));
    }
  }, [TOKEN, setUserName]);

  const handleClickLogout = () => {
    swal
      .fire({
        title: 'Get A Beer',
        text: '로그아웃 하시겠습니까?',
        showCancelButton: true,
        confirmButtonColor: '#F1B31C',
        cancelButtonColor: '#A7A7A7',
        confirmButtonText: '확인',
        cancelButtonText: '취소',
      })
      .then((result) => {
        if (result.value) {
          axios
            .post('/api/user/logout')
            .then((res) => {
              // console.log(res);
              setAccessToken('');
              setUserId('');
              setUserName('');
              delete axios.defaults.headers.Authorization;
              window.location.href = '/login';
            })
            .catch((err) => {
              console.log(err);
            });
          setAccessToken('');
          setUserId('');
          setUserName('');
          delete axios.defaults.headers.Authorization;
          window.location.href = '/login';
        }
      });
  };

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl ">
        <div className="my-8 text-center text-xl bg-white font-semibold">
          마이 페이지
        </div>
        <div className="flex gap-3 px-2 pb-8 justify-center">
          <div className="relative rounded-full w-20 h-20 self-center">
            <Image
              alt=" user profile image"
              src={userImg}
              fill
              className="object-cover rounded-full"
            />
          </div>
          <div className="p-1 self-cente">
            <div
              className="pb-2 flex"
              onClick={() =>
                router.push({
                  pathname: `/myedit`,
                })
              }
            >
              <div className="cursor-pointer hover:text-y-brown hover:">
                {name}님
              </div>
              <button className="w-5 h-5 text-y-brown cursor-pointer">
                <HiPencil className="w-5 h-5" />
              </button>
            </div>
            <div className="flex gap-2">
              <div
                className="bg-y-cream text-center py-2 w-16 rounded-lg text-xs cursor-pointer"
                onClick={() =>
                  router.push({
                    pathname: `/follower/${USERID}`,
                    query: { tap: 0 },
                  })
                }
              >
                {followerCount} 팔로워
              </div>
              <div
                className="bg-y-cream text-center py-2 w-16 rounded-lg text-xs cursor-pointer"
                onClick={() =>
                  router.push({
                    pathname: `/follower/${USERID}`,
                    query: { tap: 1 },
                  })
                }
              >
                {followingCount} 팔로잉
              </div>
            </div>
          </div>
        </div>
        <div className="m-auto max-w-md px-3 pb-20">
          <div className="border divide-y divide-gray-200 rounded-xl text-sm">
            <Link
              href={'/mypage/wish'}
              className="flex w-full p-5 rounded-t-xl justify-between hover:bg-gray-200 "
            >
              <div className="flex gap-2">
                <IoHeartOutline className="self-center w-5 h-5" />
                위시 페이지
              </div>
              <IoChevronForwardOutline className="w-5 h-5 " />
            </Link>
            <Link
              href={'/mypage/rating'}
              className="flex w-full p-5 justify-between hover:bg-gray-200 "
            >
              <div className="flex gap-2 ">
                <HiOutlinePencil className="self-center w-5 h-5" />
                나의 평가
              </div>
              <IoChevronForwardOutline className="w-5 h-5" />
            </Link>
            <Link
              href={'/mypage/pairing'}
              className="flex w-full p-5 justify-between hover:bg-gray-200 "
            >
              <div className="flex gap-2 ">
                <HiOutlineChartPie className="self-center w-5 h-5" />
                나의 페어링
              </div>
              <IoChevronForwardOutline className="w-5 h-5" />
            </Link>
            <Link
              href={'/mypage/comment'}
              className="flex w-full p-5 justify-between hover:bg-gray-200"
            >
              <div className="flex gap-2 ">
                <IoChatboxEllipsesOutline className="self-center w-5 h-5" />
                나의 댓글
              </div>
              <IoChevronForwardOutline className="w-5 h-5" />
            </Link>
            <button
              className="flex w-full p-5 justify-between hover:bg-gray-200"
              onClick={() =>
                swal.fire({
                  title: 'Get A Beer',
                  text: '서비스 준비중입니다',
                  showCancelButton: true,
                  confirmButtonColor: '#F1B31C',
                  cancelButtonColor: '#A7A7A7',
                  confirmButtonText: '확인',
                  cancelButtonText: '취소',
                })
              }
            >
              <div className="flex gap-2 ">
                <HiOutlineMapPin className="self-center w-5 h-5" />
                관심 가게
              </div>
              <IoChevronForwardOutline className="w-5 h-5" />
            </button>
            <button
              onClick={handleClickLogout}
              className="flex w-full p-5 rounded-b-xl justify-between hover:bg-gray-200"
            >
              <div className="flex gap-2 ">
                <IoLogOutOutline className="self-center w-5 h-5" />
                로그아웃
              </div>
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
