import Head from 'next/head';
import NavBar from '@/components/NavBar';
import SortBox from '@/components/selectBox/SortBox';

export default function Mypairing() {
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className="h-screen m-auto max-w-4xl">
        <main className="m-auto border-2">
          <div className="m-auto flex">
            <SortBox /> <SortBox />
          </div>
        </main>
        <div className="pb-32"></div>
        <NavBar />
      </div>
    </>
  );
}
