import Head from 'next/head';
// import SortBox from '@/components/selectBox/SortBox';
// import PairingBox from '@/components/selectBox/PairingBox';
import PairingCardController from '@/components/pairing/PairingCardController';
import axios from '@/pages/api/axios';
import { useEffect, useState } from 'react';
import { IoChevronBack } from 'react-icons/io5';
import Link from 'next/link';

export default function Pairing() {
  const [name, setName] = useState();
  const [TOKEN, setTOKEN] = useState();

  const [pariginCardPops, setPairingCardProps] = useState();
  useEffect(() => {
    const localInfo = window.localStorage.getItem('recoil-persist');
    if (localInfo !== null) {
      const tmpData = JSON.parse(localInfo);
      setTOKEN(tmpData.accessToken);
      setName(tmpData.name);
    }
  }, []);

  useEffect(() => {
    if (TOKEN !== undefined) {
      const config = {
        headers: {
          authorization: TOKEN,
        },
        withCredentials: true,
      };
      axios
        .get(`/mypage/pairing`, config)
        .then((response) => setPairingCardProps(response.data))
        .catch((error) => console.log(error));
    }
  }, [TOKEN]);

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <Link href={'/mypage'}>
          <button className="m-4">
            <IoChevronBack className="w-6 h-6" />
          </button>
        </Link>
        <div className="my-4 text-center text-xl bg-white rounded-lg max-w-4xl font-semibold">
          {name}님의 페어링
        </div>
        {/* <div className="m-auto flex">
          <PairingBox />
        </div> */}
        <PairingCardController pairingCardProps={pariginCardPops} />
        <div className="pb-32"></div>
      </main>
    </>
  );
}
