import Head from 'next/head';
import NavBar from '@/components/NavBar';
// import SortBox from '@/components/selectBox/SortBox';
import PairingBox from '@/components/selectBox/PairingBox';
import PairingCardController from '@/components/pairing/PairingCardController';

export default function Pairing() {
  const pairingCardProps = {
    data: [
      {
        beerId: 1,
        pairingId: 1,
        nickname: '김맥주',
        content: '수정된 페어링',
        thumbnail:
          'https://worldbeermarket.kr/userfiles/prdimg/2102080006_M.jpg',
        category: 'SNACK',
        likeCount: 3,
        commentCount: 0,
        isUserLikes: true,
        createdAt: '2023-02-06T00:29:14.59836',
        modifiedAt: '2023-02-06T00:31:11.1951',
      },
      {
        beerId: 1,
        pairingId: 2,
        nickname: '김맥주',
        content: '페어링 안내',
        thumbnail:
          'https://worldbeermarket.kr/userfiles/prdimg/2301050762_R.jpg',
        category: 'GRILL',
        likeCount: 2,
        commentCount: 0,
        isUserLikes: false,
        createdAt: '2023-02-06T00:35:58.259552',
        modifiedAt: '2023-02-06T00:35:58.259552',
      },
    ],
    pageInfo: {
      page: 1,
      size: 5,
      totalElements: 2,
      totalPages: 1,
    },
  };
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <div className="my-4 text-center text-xl bg-white rounded-lg max-w-4xl font-semibold">
          유미님의 페어링
        </div>
        <div className="m-auto flex">
          <PairingBox />
        </div>
        <PairingCardController pairingCardProps={pairingCardProps.data} />
        <div className="pb-32"></div>
        <NavBar />
      </main>
    </>
  );
}
