import Head from 'next/head';
import Advertise from '@/components/mainPage/Advertise';
import NavBar from '@/components/NavBar';
import PopularBeerController from '@/components/smallCards/PopularBeerController';
import BeerCategoryBtn from '@/components/mainPage/BeerCategoryBtn';
import { Input } from '@/components/inputs/Input';
import SubmitBtn from '@/components/button/SubmitBtn';
import CloseBtn from '@/components/button/CloseBtn';

export default function Main() {
  const beerProps = [
    {
      id: 1,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: 'https://worldbeermarket.kr/userfiles/prdimg/2101060009_M.jpg',
    },
    {
      id: 2,
      title: '필라이트',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: 'https://worldbeermarket.kr/userfiles/prdimg/2211160004_R.jpg',
    },
    {
      id: 3,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: 'https://worldbeermarket.kr/userfiles/prdimg/2011190018_M.jpg',
    },
    {
      id: 4,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: 'https://worldbeermarket.kr/userfiles/prdimg/2101060009_M.jpg',
    },
    {
      id: 5,
      title: '필라이트',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: 'https://worldbeermarket.kr/userfiles/prdimg/2211160004_R.jpg',
    },
  ];
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    console.log(event.target);
    console.log(event.currentTarget);
  };
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <Advertise />
        <Input type="email" placeholder="email@gmail.com" />
        <Input type="password" placeholder="비밀번호를 입력하세요." />
        <div className="grid grid-cols-2 gap-2 items-center">
          <SubmitBtn onClick={handleClick}> 등록하기 </SubmitBtn>
          <CloseBtn onClick={handleClick}> 나가기 </CloseBtn>
        </div>
        <SubmitBtn onClick={handleClick}> 등록하기 </SubmitBtn>
        <div className="m-auto">
          <BeerCategoryBtn />
          <PopularBeerController beerProps={beerProps} />
        </div>
        <div className="pb-14"></div>
        <NavBar />
      </main>
    </>
  );
}
