import Head from 'next/head';
import Advertise from '@/components/mainPage/Advertise';
// import NavBar from '@/components/NavBar';
import PopularBeerController from '@/components/smallCards/PopularBeerController';
import BeerCategoryBtn from '@/components/mainPage/BeerCategoryBtn';
import Footer from '@/components/Footer';

export default function Main() {
  const beerProps = [
    {
      id: 1,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: '/images/121.jpeg',
    },
    {
      id: 3,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: '/images/123.jpeg',
    },
    {
      id: 4,
      title: '가든 바이젠',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: '/images/124.jpeg',
    },
    {
      id: 6,
      title: '필라이트',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: '/images/146.jpeg',
    },
    {
      id: 7,
      title: '필라이트',
      category: '에일',
      country: '한국',
      level: 4.1,
      ibu: 17.5,
      image: '/images/150.jpeg',
    },
  ];

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <Advertise />
        <div className="m-auto">
          <BeerCategoryBtn />
          <PopularBeerController beerProps={beerProps} />
          <PopularBeerController beerProps={beerProps} />
        </div>
        <div className="pb-14"></div>
        <Footer />
      </main>
    </>
  );
}
