import SubmitBtn from '@/components/button/SubmitBtn';
import Link from 'next/link';
import { Input } from '@/components/inputs/Input';
import Head from 'next/head';
import { IoChevronBack } from 'react-icons/io5';

export default function Email() {
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {};
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <Link href={'/login'}>
          <button className="m-4">
            <IoChevronBack className="w-6 h-6" />
          </button>
        </Link>
        <div className="my-4 text-center text-lg bg-white rounded-lg font-semibold">
          회원가입
        </div>
        <div className="m-auto max-w-md">
          <Input type="email" placeholder="email@gmail.com" />
          <SubmitBtn onClick={handleClick}> 인증번호 전송 </SubmitBtn>
          <div className="my-5 flex justify-center gap-1.5 text-sm">
            <div className="text-y-gray font-light">05:00</div>
          </div>
        </div>
        <div className="m-auto max-w-md">
          <Input type="text" placeholder="인증번호를 입력해주세요." />
          <SubmitBtn onClick={handleClick}> 확인 </SubmitBtn>
          <div className="my-3 flex justify-center gap-1.5 text-sm">
            <div className="text-y-gray font-light">이미 계정이 있다면?</div>
            <Link href={'/login'}>
              <button className="flex text-y-brown">로그인</button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
