import SubmitBtn from '@/components/button/SubmitBtn';
import NavBar from '@/components/NavBar';
import { Input } from '@/components/inputs/Input';
import Head from 'next/head';
import { IoChevronBack } from 'react-icons/io5';

export default function Signup() {
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {};
  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <button className="m-4">
          <IoChevronBack className="w-6 h-6" />
        </button>
        <div className="my-8 text-center text-lg bg-white rounded-lg font-semibold">
          회원가입
        </div>
        <div className="m-auto max-w-md">
          <Input type="email" placeholder="email@gmail.com" />
          <Input type="text" placeholder="닉네임" />
          <Input type="password" placeholder="비밀번호" />
          <Input type="password" placeholder="비밀번호 확인" />
          <SubmitBtn onClick={handleClick}> 확인 </SubmitBtn>
          <div className="my-3 flex justify-center gap-1.5 text-sm">
            <div className="text-y-gray font-light">이미 계정이 있다면?</div>
            <button className="flex text-y-brown">로그인</button>
          </div>
        </div>
        <NavBar />
      </main>
    </>
  );
}
