version: '3.1'

services:

  redis:
    hostname: redis
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - redis-network

  getabeer:
    #    network_mode: host
    image: gnidinger/getabeer:0.0.1
    container_name: getabeer
    build: .
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
#    external: true