version: '3.1'

services:

  h2:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
    networks:
      - getabeer-network

  redis:
    hostname: redis
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - getabeer-network

  getabeer:
    #    network_mode: host
    image: gnidinger/getabeer:0.0.1
    container_name: getabeer
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/test
      # SPRING_DATASOURCE_URL: jdbc:h2:tcp://localhost:1521/demo
      SPRING_DATASOURCE_USERNAME: sa
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - getabeer-network

networks:
  getabeer-network:
#    external: true